/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gtday;

import static gtday.GTDay.headers;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hector Valentin <hectorvda@gmail.com>
 */
public class JDEditar extends javax.swing.JDialog {

    private static Tarea tarea;
    private boolean haPulsadoAceptar;
    private AbstractTableModel tableModel;
    final static String[] headers = {"Título", "Fecha límite", "Descripción"};
    /**
     * Creates new form JDEditar
     */
    public JDEditar(java.awt.Frame parent, boolean modal, Tarea t) {
        super(parent, modal);
        initComponents();
        tarea=t;
        this.haPulsadoAceptar=false;
        rellenarDatos();
    }

     /**
     * Se encarga de eliminar la tarea seleccionada de la lista actual
     *
     * @param indice número de columna seleccionada del JTable
     */
    private void eliminarTarea(String titulo) {
       int indice=jTabla.getSelectedRow();
       if(indice>=0){
           tarea.getSubtareas().remove(indice);
       }else{
           JOptionPane.showMessageDialog(this, "Para eliminar una subtarea debe primero seleccionar una", titulo, JOptionPane.INFORMATION_MESSAGE);
       }      
      jTabla.updateUI();
    }
    /**
     * Se encarga de rellenar los campos con los datos actuales de la tarea
     */
    private void rellenarDatos(){
        jTFTarea.setText(tarea.getTitulo());
        jDCFecha.setCalendar(tarea.getCalendar());
        jTFDescripcion.setText(tarea.getDescripcion());
        rellenarTabla();
    }
    
     /**
     * Se encarga de rellenar el modelo de la Tabla indicada
     */
    private void rellenarTabla() {
        TableColumnModel tcm;
        if(tarea.getSubtareas()!=null && !tarea.getSubtareas().isEmpty()){
            tableModel = new JDEditar.TableModel(tarea.getSubtareas());
            jTabla.setModel(tableModel);
        }
        tcm = jTabla.getColumnModel();
        for (int col = 0; col < headers.length; col++) {
            tcm.getColumn(col).setHeaderValue(headers[col]);
        }
        jTabla.updateUI();
    }
    
    public boolean haPulsadoAceptar(){
        return this.haPulsadoAceptar;
    }
    
    public Tarea getTarea(){
        return tarea;
    }
    
    private void actualizarTarea(){
        tarea.setDescripcion(jTFDescripcion.getText());
        tarea.setFecha_Limite(jDCFecha.getCalendar());
        tarea.setTitulo(jTFTarea.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFTarea = new javax.swing.JTextField();
        jTFDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jBAdd = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        jLabel1.setText("Tarea:");

        jLabel2.setText("Descripción:");

        jTFTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTareaActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Límite:");

        jBAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtday/añadir.png"))); // NOI18N
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gtday/eliminar.png"))); // NOI18N
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDCFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTFDescripcion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBGuardar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAdd)
                            .addComponent(jBEliminar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTFTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTareaActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        JDNuevaTarea jdnt = new JDNuevaTarea(null, true);
        jdnt.setVisible(true);
        //Si ha pulsado aceptar se añadirá la tarea creada al estado actual
        if (jdnt.haPulsadoAceptar()) {
            tarea.addSubtarea(jdnt.getTarea());
        }
        rellenarTabla();
    }//GEN-LAST:event_jBAddActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
         if (jTabla.getSelectedRow() >= 0) {
            JDConfirmaEliminar jdce = new JDConfirmaEliminar(null, true);
            jdce.setVisible(true);
            if (jdce.haPulsadoAceptar()) {
                eliminarTarea((String) jTabla.getValueAt(jTabla.getSelectedRow(), 0));
                rellenarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una tarea para poder eliminarla", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.haPulsadoAceptar=false;
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        actualizarTarea();
        this.haPulsadoAceptar=true;
        this.setVisible(false);
    }//GEN-LAST:event_jBGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEditar dialog = new JDEditar(new javax.swing.JFrame(), true, tarea);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
      /**
     * Inner class (clase interna) que contiene lo necesario para montar el
     * modelo de datos del JTable
     */
    class TableModel extends AbstractTableModel {

        ArrayList<Tarea> datos;

        /**
         * Constructor principal de la Inner class
         *
         * @param param lista de datos de tipo tarea a cargar
         */
        public TableModel(ArrayList<Tarea> param) {
            datos = param;
        }

        @Override
        public int getRowCount() {
            return datos.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public Object getValueAt(int i, int i1) {
            Object devuelto = null;
            switch (i1) {
                case 0:
                    devuelto = datos.get(i).getTitulo();
                    break;
                case 1:
                    devuelto = datos.get(i).getFecha_Limite();
                    break;
                case 2:
                    devuelto = datos.get(i).getDescripcion();
                    break;
            }
            return devuelto;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFTarea;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
